### ISSUE TITLE
import_fs.default.cpSync is not a function

### ISSUE THREAD

**Issue by MezianeKhalil** [vercel/turborepo#2305]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

import_fs.default.cpSync is not a function..... when try to setup new turborepo app in step 3 after choosing name of app & package manager npm(8.19.2)

### Expected Behavior

should be installed everything

### To Reproduce

![image](https://user-images.githubusercontent.com/67861260/197339597-9b7e249e-f4a0-4aa9-8dbf-999da411c2ac.png)

**Comment by tknickman** [comment]
Use node 16 or greater for now. We'll add support for Node 14 shortly.

**Comment by MezianeKhalil** [comment]
> Use node 16 or greater for now. We'll add support for Node 14 shortly.

i use v16 & 18 give me same issue. but after using v17 its work fine. thanke you

**Comment by thanveershah** [comment]
Got the same error, Will  upgrade node

**Comment by peksi** [comment]
For me didn't work with `v16.6.2` but the problem was solved with `16.13.0` 🤷‍♀️
