### ISSUE TITLE
@turbo/gen@2.8.8 no longer able to import @inquirer/prompts in config.ts

### ISSUE THREAD

**Issue by jahands** [vercel/turborepo#11855]
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/jahands/turbo-gen-bug-20250214

### Which canary version will you have in your reproduction?

@turbo/gen@2.8.8 (there are no canaries for @turbo/gen at this time)

### Expected behavior

Ability to use input/search etc from @inquirer/prompts library

### Actual behavior

```
$ bunx @turbo/gen@2.8.8

>>> Modify "turbo-gen-bug-20250214" using custom generators

>>> ResolveMessage: Cannot find module '@inquirer/prompts' from '/Users/jh/src/turbo-gen-bug-20250214/turbo/generators/config.ts'
>>> No generators found.

? Would you like to add a config with a sample custom generator to turbo-gen-bug-20250214? (Y/n)
```

### To Reproduce

```sh
git clone https://github.com/jahands/turbo-gen-bug-20250214
cd turbo-gen-bug-20250214
bun install
bunx @turbo/gen@2.8.7 # works
bunx @turbo/gen@2.8.8 # doesn't work
```

### Additional context

Works on 2.8.7, broke on 2.8.8
No canary releases for @turbo/gen at this time to test it on.

**Comment by anthonyshew** [comment]
Hey, Jacob. My bad, I didn't catch this. v2.8.9-canary.2 is showing this as fixed and the v2.8.9 is going up as I type this. Sorry for the disruption.

**Comment by jahands** [comment]
No worries!! Thanks for the quick fix!

**Comment by jahands** [comment]
@anthonyshew oh hey turns out I still have an issue where relative imports fail :( I updated the repro with 2.8.11-canary.10 to show this new failure scenario

**Comment by anthonyshew** [comment]
Can you try v2.8.17-canary.1 or above? I think I fixed this last night.

**Comment by jahands** [comment]
Works now! Thanks!
